### ISSUE TITLE
open 需要指定 newline 参数

### ISSUE THREAD

**Issue by XIVN1987** [mysterywolf/formatting#13]
两句 `file_temp = open(temp_file, 'w', encoding='utf-8')` 应该改成 `file_temp = open(temp_file, 'w', encoding='utf-8', newline='\n')`

否则在 windows 上执行时文件后缀依然保持 '\r\n' 不变

**Comment by mysterywolf** [comment]
https://github.com/mysterywolf/formatting/commit/9b51ace1336dd161303c77a423b37650c4f5cfca

**Comment by mysterywolf** [comment]
已修复 感谢issue
