### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by CuttySark1869** [mysterywolf/formatting#6]
It might be useful to say that this tool only supports python 3 in readme.

**Comment by mysterywolf** [comment]
https://github.com/mysterywolf/formatting/commit/7f2219f5eaa3068b2fb86641c402d45e52b78c19
感谢已经增加

**Comment by CuttySark1869** [comment]
Jianting,

你好，感谢修改。formatting 很好用，希望能过长期维护和更新。

对 rt-thread PR #6254 所提的意见已经修改，只是
rt_vsnprintf()尚有疑问写在PR的comment里了。还有rsicv-64似乎没有通过测试，我还在研究原因。

顺便介绍我自己。我在英国做power
electronics，对这个行业长期以来用笨拙手动的方法进行软件开发深感痛苦，希望能把嵌入式领域先进的工具链和方法论移植过来。发现这个移植并不是trivial的，主要有三点，一是power
electronics对实时性的要求更高（微秒甚至更低）；二是power
electronics对外设的抽象可能不太一样，特别是PWM外设；第三是有些power electronics应用对存储资源是敏感的。

我和上海交大的一个小伙伴Qi
Yu准备着手解决这两个问题。思路是这样的，第一是对全局中断进行处理，设置一种超级中断不会被关闭，独立于OS之外运行，超级中断中不会使用任何OS相关的服务，用ping-pong机制跟OS对话，以解决实时性问题。第二是针对power
electronics的应用需求扩展对硬件的抽象。第三是定义一些OS的子集，比如只有状态机没有调度器，或者只使用非常简单的调度器。
https://github.com/OpenPowerware 这是的我们Organisation。

We appreciate any comments from you.

Kind Regards,
Yunjie
